name: Push Deep Security to GCP Container Registry

on:
  push:
    branches:
      - main
    paths:
      - "deep_security/**"

jobs:
  deploy:
    name: Build & Deploy Factory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker Image
        working-directory: ./deep_security
        run: |
          docker build --platform linux/amd64 -t gcr.io/junction-hack-50b8a/deep-security .

      - name: Push Docker Image
        run: |
          docker push gcr.io/junction-hack-50b8a/deep-security
